### PR TITLE
fix: add default value validation for AI policy configuration

### LINKED ISSUE #11559: Invalid JSON in AI Policy field defaults not caught by validation
### kgateway version

main

### Kubernetes Version

N/A

### Describe the bug

We have a validation gap where invalid JSON in AI Policy field defaults is not caught by either proto validation or XDS validation. This allows invalid configurations to pass validation and potentially cause runtime errors.

Given an AI Policy with invalid JSON in a field default:
```yaml
transformationTemplate:
  mergeJsonKeys:
    jsonKeys:
      custom_list:
        tmpl:
          text: '{{ default(custom_list, "[1,2,3") }}'  # Missing closing bracket
```

The following AI policy snippet reproduces this scenario:

```yaml
  ai:
    routeType: CHAT
    defaults:
    - field: "custom_list"
      value: "[1,2,3"  # Invalid JSON array missing closing bracket
```

And the corresponding code wraps that custom list with the `default` inja template:

```
		var tmpl string
		if field.Override != nil && *field.Override {
			tmpl = string(marshalled)
		} else {
			// Inja default function will use the default value if the field provided is falsey
			tmpl = fmt.Sprintf("{{ default(%s, %s) }}", field.Field, string(marshalled))
		}
```

### Expected Behavior

Surprised this isn't caught by xDS validation like other transformation templates that are structurally invalid. Potentially the usage of `default` is relevant? Didn't dive too deep

### Steps to reproduce the bug

See the following reproducer:

<details>

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: example-gateway
  namespace: gwtest
spec:
  gatewayClassName: kgateway
  listeners:
  - name: http
    port: 8080
    protocol: HTTP
    hostname: www.example.com
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
  namespace: gwtest
type: Opaque
data:
  Authorization: c2stdGVzdC1hYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5ejEyMzQ= # Base64 encoded "sk-test-abcdefghijklmnopqrstuvwxyz1234"
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: Backend
metadata:
  name: example-ai-backend
  namespace: gwtest
spec:
  type: AI
  ai:
    llm:
      provider:
        openai:
          model: "gpt-4"
          authToken:
            kind: "SecretRef"
            secretRef:
              name: openai-secret
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: invalid-ai-route
  namespace: gwtest
spec:
  parentRefs:
  - name: example-gateway
  rules:
  - backendRefs:
    - name: example-ai-backend
      kind: Backend
      group: gateway.kgateway.dev
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: invalid-ai-field-default
  namespace: gwtest
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: invalid-ai-route
  ai:
    routeType: CHAT
    defaults:
    - field: "custom_list"
      value: "[1,2,3"  # Invalid JSON array missing closing bracket
```

</details>

### Additional Environment Detail

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by zhengkezhou1**
# Description

Fixes #11559

# Change Type

```
/kind bug_fix
```

# Changelog

```release-note
NONE
```

# Additional Notes

### CODE REVIEW

File: internal/kgateway/extensions2/plugins/trafficpolicy/ai_policy.go [hunk 1]
```diff
@@ -161,12 +161,30 @@ func applyDefaults(
 		if err != nil {
 			return err
 		}
+
+		trimmed := strings.TrimSpace(field.Value)
```
Comment (shashankram) [inline internal/kgateway/extensions2/plugins/trafficpolicy/ai_policy.go]: Could you add comments on what this block of code is attempting to do?

Comment (shashankram) [inline internal/kgateway/extensions2/plugins/trafficpolicy/ai_policy.go]:
```suggestion
		value := strings.TrimSpace(field.Value)
```

File: internal/kgateway/extensions2/plugins/trafficpolicy/ai_policy.go [hunk 2]
```diff
@@ -161,12 +161,30 @@ func applyDefaults(
...
+		hasJsonPrefix := strings.HasPrefix(trimmed, "{") || strings.HasPrefix(trimmed, "[")
+		hasJsonSuffix := strings.HasSuffix(trimmed, "}") || strings.HasSuffix(trimmed, "]")
```
Comment (shashankram) [inline internal/kgateway/extensions2/plugins/trafficpolicy/ai_policy.go]: More readable to create `hasJSONPrefix` and `hasJSONSuffix` helper functions and use them

File: internal/kgateway/extensions2/plugins/trafficpolicy/ai_policy.go [hunk 3]
```diff
@@ -161,12 +161,30 @@ func applyDefaults(
...
+			}
+		}
 		var tmpl string
 		if field.Override != nil && *field.Override {
-			tmpl = string(marshalled)
+			if strings.HasPrefix(trimmed, "{") || strings.HasPrefix(trimmed, "[") {
+				tmpl = field.Value
+			} else {
+				tmpl = string(marshalled)
+			}
```
Comment (shashankram) [inline internal/kgateway/extensions2/plugins/trafficpolicy/ai_policy.go]: add a comment to describe the logic

File: internal/kgateway/extensions2/plugins/trafficpolicy/ai_policy.go [hunk 4]
```diff
@@ -161,12 +161,30 @@ func applyDefaults(
...
 		} else {
 			// Inja default function will use the default value if the field provided is falsey
-			tmpl = fmt.Sprintf("{{ default(%s, %s) }}", field.Field, string(marshalled))
+			if strings.HasPrefix(trimmed, "{") || strings.HasPrefix(trimmed, "[") {
+				tmpl = fmt.Sprintf("{{ default(%s, %s) }}", field.Field, field.Value)
+			} else {
+				tmpl = fmt.Sprintf("{{ default(%s, %s) }}", field.Field, string(marshalled))
+			}
```
Comment (shashankram) [inline internal/kgateway/extensions2/plugins/trafficpolicy/ai_policy.go]: add a comment to describe the logic

File: internal/kgateway/extensions2/plugins/trafficpolicy/ai_policy_test.go [hunk 5]
```diff
@@ -238,6 +239,128 @@ func TestProcessAITrafficPolicy(t *testing.T) {
...
+			aiConfig: &v1alpha1.AIPolicy{
+				Defaults: []v1alpha1.FieldDefault{
+					{
+						Field: "bad object",
+						Value: `"model":"gpt-4"}`,
+					},
+				},
+			},
+			err: errors.New("field bad object contains invalid JSON string: model\":\"gpt-4\"}"),
+		},
```
Comment (shashankram) [inline internal/kgateway/extensions2/plugins/trafficpolicy/ai_policy_test.go:347]: we need to test non-JSON values as well

File: test/kubernetes/e2e/features/aiextension/suite.go [hunk 6]
```diff
@@ -108,6 +109,27 @@ func (s *tsuite) AfterTest(suiteName, testName string) {
 	}
 }
 
+func (s *tsuite) TestDefaults() {
```
Comment (shashankram) [inline test/kubernetes/e2e/features/aiextension/suite.go]: Why do you need an e2e test to validate JSON? Can you update internal/kgateway/translator/gateway/gateway_translator_test.go instead?

File: internal/kgateway/translator/gateway/gateway_translator_test.go [hunk 7]
```diff
@@ -223,6 +223,16 @@ var _ = DescribeTable("Basic GatewayTranslator Tests",
...
+	Entry(
+		"TrafficPolicy with ai invalided default values",
+		translatorTestCase{
+			inputFile:  "traffic-policy/ai-invalid-default-value.yaml",
+			outputFile: "traffic-policy/ai-invalid-default-value.yaml",
+			gwNN: types.NamespacedName{
+				Namespace: "infra",
+				Name:      "example-gateway",
+			},
+		}),
```
Comment (zhengkezhou1) [inline internal/kgateway/translator/gateway/gateway_translator_test.go]: Is there any way to verify the exception when translation fails?

File: test/kubernetes/e2e/features/aiextension/suite.go (hunk 6 above)
Comment (zhengkezhou1) [reply test/kubernetes/e2e/features/aiextension/suite.go]: I've added the test cases to `gateway_translator_test.go`,removed them.

File: internal/kgateway/translator/gateway/gateway_translator_test.go (hunk 7 above)
Comment (npolshakova) [reply internal/kgateway/translator/gateway/gateway_translator_test.go]: You can potentially do a check similar to this if there's an error in the status: https://github.com/kgateway-dev/kgateway/blob/7fd6a2515961db2a0856c67ca545c0b6def0f214/internal/kgateway/translator/gateway/gateway_translator_test.go#L902

Comment (npolshakova) [reply internal/kgateway/translator/gateway/gateway_translator_test.go]: I think since the traffic policy doesn't have the error in the status, this can just confirm the output is as expected and the error assertions can happen in ai_policy_test.go

Comment (timflannagan) [reply internal/kgateway/translator/gateway/gateway_translator_test.go]: @npolshakova I think we'd see an error surface on the TP & HTTPRoute status (now that #11535 has landed), right? preProcessAITrafficPolicy is called during the builder's Translate method and we propagate those errors to the policy IR.

Comment (timflannagan) [reply internal/kgateway/translator/gateway/gateway_translator_test.go]: Yeah confirmed locally the TP rejects the invalid config from the original issue:

```
...
conditions:
- lastTransitionTime: "2025-07-09T20:29:22Z"
  message: 'field custom_list contains invalid JSON string: [1,2,3'
  observedGeneration: 1
  reason: Invalid
  status: "False"
  type: Accepted
```

I think we'd need to fix the merge conflict & merge with main to see the HTTPRoute updated as well. Right now it's reporting an Accepted=true state on my local cluster.

**Comment by timflannagan** [comment]
@zhengkezhou1 Looks like there's some merge conflicts with the gateway translator suite. Can we also merge with main? I think we'd see the HTTPRoute status get affected by this change in addition to the error reflecting on the TP status.

File: internal/kgateway/translator/gateway/gateway_translator_test.go (hunk 7 above)
Comment (zhengkezhou1) [reply internal/kgateway/translator/gateway/gateway_translator_test.go]: Here's what I observed when running `gateway_translator_test.go`:

```
2025-07-13T15:05:41.073939Z	info	krt	Collection[ir.BackendObjectIR,ir.BackendObjectIR] synced	owner=Collection[ir.BackendObjectIR,ir.BackendObjectIR]
{"time":"2025-07-13T23:05:41.075489+08:00","level":"ERROR","msg":"error translating gateway extension","component":"plugin/trafficpolicy","namespace":"infra","name":"override-default-value-validation-invalid-slices-test","error":"field invalid_slices contains invalid JSON string: [1,2,3"}
2025-07-13T15:05:41.075503Z	info	krt	WaypointKubeServices synced	owner=WaypointKubeServices
2025-07-13T15:05:41.075509Z	info	krt	KubernetesServiceBackends synced	owner=KubernetesServiceBackends
2025-07-13T15:05:41.075512Z	info	krt	WaypointLogicalServices synced
{"time":"2025-07-13T23:05:41.075525+08:00","level":"ERROR","msg":"error translating gateway extension","component":"plugin/trafficpolicy","namespace":"infra","name":"default-value-validation-invalid-object-test","error":"field invalid_object contains invalid JSON string: \"model\":\"gpt-4\"}"}
{"time":"2025-07-13T23:05:41.075536+08:00","level":"ERROR","msg":"error translating gateway extension","component":"plugin/trafficpolicy","namespace":"infra","name":"default-value-validation-invalid-slices-test","error":"field invalid_slices contains invalid JSON string: [1,2,3"}
{"time":"2025-07-13T23:05:41.075545+08:00","level":"ERROR","msg":"error translating gateway extension","component":"plugin/trafficpolicy","namespace":"infra","name":"override-default-value-validation-invalid-object-test","error":"field invalid_object contains invalid JSON string: \"model\":\"gpt-4\"}"}
```

The issue is that these errors are currently only consumed by the logger, and there's no way to assert them within the test itself:

```
FEntry("TrafficPolicy with ai invalided default values", "traffic_policy_ai_invalid_default_value.yaml",
		map[types.NamespacedName]string{
			{Name: "default-value-validation-invalid-object-test", Namespace: "infra"}:      "field invalid_object contains invalid JSON string: \\\"model\\\":\\\"gpt-4\\\"}",
			{Name: "default-value-validation-invalid-slices-test", Namespace: "infra"}:      "field invalid_slices contains invalid JSON string: [1,2,3",
			{Name: "override-default-value-validation-invalid-slices-test", Namespace: "infra"}: "field invalid_slices contains invalid JSON string: [1,2,3",
			{Name: "override-default-value-validation-invalid-object-test", Namespace: "infra"}: "field invalid_object contains invalid JSON string: \\\"model\\\":\\\"gpt-4\\\"}",
		}),

[FAILED] Expected an error, got nil
```

**Review by timflannagan — COMMENTED** [review]
@zhengkezhou1 Sorry, this PR got lost in the notifications. We're almost there except for the translator test case added here. A couple of notes inline:

- We should add the test case to the regular `DescribeTable("Basic",` suite defined at the top of the file instead of having it located with the delegation describe table
- Additionally, I validated locally that we can assert the error is propagated to the HTTPRoute status after merging with main

For the former, here is what I had in mind:

```go
DescribeTable("Basic",
    ...
	Entry(
		"TrafficPolicy with ai invalided default values",
		translatorTestCase{
			inputFile:  "traffic-policy/ai-invalid-default-value.yaml",
			outputFile: "traffic-policy/ai-invalid-default-value.yaml",
			gwNN: types.NamespacedName{
				Namespace: "infra",
				Name:      "example-gateway",
			},
			assertReports: func(gwNN types.NamespacedName, reportsMap reports.ReportMap) {
				// we expect the httproute to reflect an invalid status
				route := &gwv1.HTTPRoute{
					ObjectMeta: metav1.ObjectMeta{
						Name:      "example-route",
						Namespace: "infra",
					},
				}
				routeStatus := reportsMap.BuildRouteStatus(context.Background(), route, wellknown.DefaultGatewayClassName)
				Expect(routeStatus).NotTo(BeNil())
				Expect(routeStatus.Parents).To(HaveLen(1))

				partiallyInvalid := meta.FindStatusCondition(routeStatus.Parents[0].Conditions, string(gwv1.RouteConditionPartiallyInvalid))
				Expect(partiallyInvalid).NotTo(BeNil())
				Expect(partiallyInvalid.Status).To(Equal(metav1.ConditionTrue))
				Expect(partiallyInvalid.Reason).To(Equal(string(gwv1.RouteReasonUnsupportedValue)))
				Expect(partiallyInvalid.Message).To(ContainSubstring("Dropped Rule (0)"))
				Expect(partiallyInvalid.ObservedGeneration).To(Equal(int64(0)))
			},
		}),
```

And then the subsequent input I used to make sure everything was hooked up correctly:

<details>

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: example-gateway
  namespace: infra
spec:
  gatewayClassName: kgateway
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: example-route
  namespace: infra
spec:
  parentRefs:
  - name: example-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: example-svc
      port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: example-svc
  namespace: infra
spec:
  selector:
    test: test
  ports:
    - protocol: TCP
      port: 80
      targetPort: test
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: test-policy
  namespace: infra
  generation: 42
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: example-route
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: default-value-validation-invalid-slices-test
  namespace: infra
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: example-route
  ai:
    defaults:
      - field: "invalid_slices"
        value: "[1,2,3"
```

</details>

Note that we needed the Gateway/HTTPRoute/Service manifests in addition to the invalid TrafficPolicy case(s) you had in the ai-invalid-default-value.yaml test file. I simplified that file to just test the `invalid_slices` as well.

File: internal/kgateway/translator/gateway/gateway_translator_test.go (hunk 7 above)
Comment (timflannagan) [reply internal/kgateway/translator/gateway/gateway_translator_test.go]: Whoops, meant to reply here. See https://github.com/kgateway-dev/kgateway/pull/11594#pullrequestreview-3044153155 for what we'd need to do here.

Comment (zhengkezhou1) [reply internal/kgateway/translator/gateway/gateway_translator_test.go]: Oh I see, thanks for reminding me, I will finish this soon.

File: internal/kgateway/translator/gateway/gateway_translator_test.go [hunk 8]
```diff
@@ -195,6 +196,37 @@ var _ = DescribeTable("Basic",
...
+				Expect(partiallyInvalid).NotTo(BeNil())
+				Expect(partiallyInvalid.Status).To(Equal(metav1.ConditionTrue))
+				Expect(partiallyInvalid.Reason).To(Equal(string(gwv1.RouteReasonUnsupportedValue)))
+				Expect(strings.Count(partiallyInvalid.Message, `field invalid_object contains invalid JSON string: "model":"gpt-4"}`)).To(Equal(2),
+					"Expected 'invalid_object' message to appear exactly twice")
+				Expect(strings.Count(partiallyInvalid.Message, `field invalid_slices contains invalid JSON string: [1,2,3`)).To(Equal(2),
+					"Expected 'invalid_slices' message to appear exactly twice")
+				Expect(partiallyInvalid.ObservedGeneration).To(Equal(int64(0)))
+			},
+		}),
```
Comment (zhengkezhou1) [inline internal/kgateway/translator/gateway/gateway_translator_test.go:229]: Due to there being four traffic policies in the test, simply asserting the presence of `field invalid_object contains invalid JSON string` and `field invalid_slices contains invalid JSON string` in the message isn't accurate enough. The actual situation is that each of them appeared twice.

Comment (timflannagan) [reply internal/kgateway/translator/gateway/gateway_translator_test.go:229]: I _think_ this is fine for now, and it covers more ground, but I'm worried we risk some test brittleness with this approach in the case we change the error message. That's the same rationale on why we prefer substring assertions over direct string assertions. I'm cool with this approach though, and it's an easy refactor candidate if we do run into some brittleness in the future.

**Comment by timflannagan** [comment]
@zhengkezhou1 Looks like the linter is complaining about an import that we'll need to fix. Let me know once we're back in business and I'll re-approve this PR.

**Comment by zhengkezhou1** [comment]
@timflannagan I fixed the import problem.

**Review by timflannagan — APPROVED** [review]
