### PR TITLE
*: Fix CRD metadata labels

### LINKED ISSUE #10663: Inconsistent CRD labels
See https://github.com/kgateway-dev/kgateway/blob/4ea2656d1021887c7484c9bc983f16ea0b256493/api/v1alpha1/direct_response_types.go#L14 for a concrete example

Related to #10597.

### PR DESCRIPTION
**Pull request by timflannagan**
This commit updates the DRR and GWParams CRDs labels to be consistent with the rest of the project's CRDs.

# Description

A quick follow-up to #10597 and replaces the gloo-gateway labels being referenced in several CRDs.

Closes #10663.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: api/v1alpha1/direct_response_types.go [hunk 1]
```diff
@@ -11,7 +11,7 @@ import (
 //
 // +genclient
 // +kubebuilder:object:root=true
-// +kubebuilder:metadata:labels={app=gloo-gateway,app.kubernetes.io/name=gloo-gateway}
+// +kubebuilder:metadata:labels={app=gateway,app.kubernetes.io/name=gateway}
```
Comment (yuval-k) [inline api/v1alpha1/direct_response_types.go:14]: should the value be `kgateway` instead of `gateway`?

Comment (timflannagan) [reply api/v1alpha1/direct_response_types.go:14]: kgateway sgtm. i'll push up an update.

**Review by jenshu — APPROVED** [review]
