### PR TITLE
agentgateway: implement BackendTLSPolicy

### LINKED ISSUE #12141: agentgateway: backend name is not distinct
### kgateway version

.

### Kubernetes Version

.

### Describe the bug

```yaml
apiVersion: gateway.kgateway.dev/v1alpha1
kind: Backend
metadata:
  name: mcp
  namespace: mcp-servers
spec:
  type: MCP
  mcp:
    name: mcp
    targets:
    - static:
        name: mcp
        host: test.com
        port: 443
        protocol: StreamableHTTP
```

The name `mcp` is used as a key multiple times. We need the inner Backend object to get a distinct key

cc @npolshakova @shashankram I mentioned this to one of you, forgot who

### Expected Behavior

.

### Steps to reproduce the bug

.

### Additional Environment Detail

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by shashankram**
# Description
- Implements BackendTLSPolicy plugin
- Updates MCP Backend API to use named targets for sectionName based attachments.
- Renames nested selector fields to avoid stutter and fixes inconsistencies.
- Adds `kgateway.dev/mcp-path` annotation to override the HTTP path to use for selector based MCP backends.
- Fixes a bug in the agentgateway syncer for a case where the Service and Pod name are the same.

# Change Type

```
/kind cleanup
/kind new_feature
```

# Changelog

```release-note
NONE
```

# Additional Notes
Part of #12040
Resolves #12141

### CODE REVIEW

File: pkg/agentgateway/plugins/backend_tls_plugin.go [hunk 1]
```diff
@@ -0,0 +1,175 @@
...
+	var policies []ADPPolicy
+
+	for idx, target := range btls.Spec.TargetRefs {
+		var policyTarget *api.PolicyTarget
+
+		switch string(target.Kind) {
+		case wellknown.BackendGVK.Kind:
+			// The target defaults to <backend-namespace>/<backend-name>.
+			// If SectionName is specified to select a specific target in the Backend,
+			// the target becomes <backend-namespace>/<section-name>
```
Comment (howardjohn) [inline pkg/agentgateway/plugins/backend_tls_plugin.go]: I think this is correct but FYI it only works due to another bug: https://github.com/kgateway-dev/kgateway/issues/12141. Basically we cannot have `<backend-namespace>/<section-name>` and `<backend-namespace>/<backend-name>` both be valid since section-name and backend-name can collide

File: pkg/agentgateway/plugins/backend_tls_plugin.go [hunk 2]
```diff
@@ -0,0 +1,175 @@
...
+					},
+				}
+			}
+
+		default:
+			logger.Warn("unsupported target kind", "kind", target.Kind, "policy", btls.Name)
+			continue
+		}
+
+		// TODO: support btls.Spec.Validation.Hostname.
```
Comment (howardjohn) [inline pkg/agentgateway/plugins/backend_tls_plugin.go]: This is done, can remove todo

File: pkg/agentgateway/plugins/backend_tls_plugin.go [hunk 3]
```diff
@@ -0,0 +1,175 @@
...
+		// Needs AGW support.
+
+		caCert, err := getBackendTLSCACert(krtctx, cfgmaps, btls)
+		if err != nil {
+			logger.Error("error getting backend TLS CA cert", "policy", client.ObjectKeyFromObject(btls), "error", err)
+			return nil
+		}
+		var hostname *wrapperspb.StringValue
+		if sni := string(btls.Spec.Validation.Hostname); sni != "" {
```
Comment (howardjohn) [inline pkg/agentgateway/plugins/backend_tls_plugin.go]: the check is fine but FWIW the GW API currently has MinLenth=1 on this field

File: pkg/agentgateway/plugins/backend_tls_plugin.go [hunk 4]
```diff
@@ -0,0 +1,175 @@
...
+			return nil, fmt.Errorf("unsupported wellKnownCACertificates: %v", kind)
+		}
+	}
+
+	// One of WellKnownCACertificates or CACertificateRefs will always be specified (CEL validated)
+	if len(validation.CACertificateRefs) == 0 {
+		// should never happen as this is CEL validated. Only here to prevent panic in tests
+		return nil, errors.New("BackendTLSPolicy must specify either wellKnownCACertificates or caCertificateRefs")
+	}
+	// Only 1 CACertificateRefs for Gateway API Core support
```
Comment (howardjohn) [inline pkg/agentgateway/plugins/backend_tls_plugin.go]: Fine with this but fwiw we could do multiple if we want, would just fetch them all and join with `\n` I think

Comment (howardjohn) [reply pkg/agentgateway/plugins/backend_tls_plugin.go]: Not sure why we didn't do this in istio/kgateway, we could do the same with Envoy :thinking:

Comment (howardjohn) [reply pkg/agentgateway/plugins/backend_tls_plugin.go]: Ah for Istio at least it would be ~hard since we don't inline the bytes but instead reference them via sds.

**Review by howardjohn — APPROVED** [review]

File: pkg/agentgateway/plugins/backend_tls_plugin.go (hunk 4 above)
Comment (shashankram) [reply pkg/agentgateway/plugins/backend_tls_plugin.go]: I can join with `\n` like you suggest

File: pkg/agentgateway/plugins/backend_tls_plugin.go (hunk 3 above)
Comment (shashankram) [reply pkg/agentgateway/plugins/backend_tls_plugin.go]: missed the validation in the API. Since this is a required field, setting this always

File: pkg/agentgateway/plugins/backend_tls_plugin.go (hunk 1 above)
Comment (shashankram) [reply pkg/agentgateway/plugins/backend_tls_plugin.go]: Fixed

File: api/annotations/agentgateway.go [hunk 5]
```diff
@@ -0,0 +1,4 @@
+package annotations
+
+// MCPServiceHTTPPath is the annotation used to specify the HTTP path for the MCP service
+const MCPServiceHTTPPath = "kgateway.dev/mcp-path"
```
Comment (npolshakova) [inline api/annotations/agentgateway.go:4]: Do we want to move the other annotations to this directory then?

Comment (shashankram) [reply api/annotations/agentgateway.go:4]: Which ones? I don't mind moving them

File: api/v1alpha1/mcp_backend.go [hunk 6]
```diff
@@ -4,70 +4,63 @@ import metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
...
 	Targets []McpTargetSelector `json:"targets"`
 }
 
 // McpTargetSelector defines the MCP target to use for this backend.
-// +kubebuilder:validation:XValidation:message="exactly one of static or selectors must be set",rule="!(has(self.static) && has(self.selectors))"
+// +kubebuilder:validation:ExactlyOneOf=selector;static
 type McpTargetSelector struct {
-	// Selectors is the selector logic to search for MCP targets with the mcp app protocol.
+	// Name of the MCP target.
+	Name string `json:"name"`
```
Comment (npolshakova) [inline api/v1alpha1/mcp_backend.go:19]: So if an MCPTarget is using the selector and we have a policy attached, all selected MCP servers will get the policy applied? Is there a way to apply the policy to a specific k8s service vs. all the selected services?

File: internal/kgateway/agentgatewaysyncer/testdata/inputs/backend/backend-tls.yaml [hunk 7]
```diff
@@ -0,0 +1,126 @@
...
+        port: 8000
+        protocol: StreamableHTTP
+    - name: mcp-selector
+      selector:
+        service:
+          matchLabels:
+            app: mcp-app
+---
+apiVersion: gateway.networking.k8s.io/v1alpha3
+kind: BackendTLSPolicy
```
Comment (npolshakova) [inline internal/kgateway/agentgatewaysyncer/testdata/inputs/backend/backend-tls.yaml:75]: Does BackendTLSPolicy also support extensionRef?

File: internal/kgateway/extensions2/plugins/backend/agentgateway/translate.go [hunk 8]
```diff
@@ -272,34 +273,35 @@ func buildMCPIr(krtctx krt.HandlerContext, be *v1alpha1.Backend, services krt.Co
 	// Process each target selector
 	for _, targetSelector := range be.Spec.MCP.Targets {
 		// Handle static targets
-		if targetSelector.StaticTarget != nil {
-			staticBackendRef := be.Namespace + "/" + targetSelector.StaticTarget.Name
+		if targetSelector.Static != nil {
+			// Since policies can target specific targets within an MCP backend using SectionName,
+			// the key for the target must include the Backend Name to prevent collisions with
+			// policies targeting the entire Backend that have the same name as the target
+			staticBackendRef := be.Namespace + "/" + be.Name + "/" + targetSelector.Name
```
Comment (npolshakova) [inline internal/kgateway/extensions2/plugins/backend/agentgateway/translate.go]: Can we add this to https://github.com/kgateway-dev/kgateway/blob/ca9ad1efe6b8dda6193daf6b042ade5b59692abc/pkg/agentgateway/utils/utils.go?

File: api/v1alpha1/mcp_backend.go (hunk 6 above)
Comment (shashankram) [reply api/v1alpha1/mcp_backend.go:19]: For selector based targets, policies are applied to the leaf resource, i.e. Service. BackendTLSPolicy's SectionName only applies to Static targets such that they get mapped to the StaticBackend type. It is not possible to select all targets with a single policy for MCP backends since a BackendTLSPolicy is only attachable to a single hostname.

File: internal/kgateway/agentgatewaysyncer/model.go [hunk 9]
```diff
@@ -107,8 +108,12 @@ func getADPResourceName(r *api.Resource) string {
 		return "backend/" + t.Backend.GetName()
 	case *api.Resource_Route:
 		return "route/" + t.Route.GetKey()
+	case *api.Resource_Policy:
```
Comment (npolshakova) [inline internal/kgateway/agentgatewaysyncer/model.go:111]: Nice!

File: internal/kgateway/agentgatewaysyncer/testdata/inputs/backend/backend-tls.yaml (hunk 7 above)
Comment (shashankram) [reply internal/kgateway/agentgatewaysyncer/testdata/inputs/backend/backend-tls.yaml:75]: ExtensionRef based attachments is legacy behavior in kgw, so we don't need to carry forward that behavior in agw.

File: test/kubernetes/e2e/features/backendtls/suite.go [hunk 10]
```diff
@@ -69,31 +64,49 @@ var (
...
 
-var _ e2e.NewSuiteFunc = NewTestingSuite
-
-type clientTlsTestingSuite struct {
+type tsuite struct {
 	suite.Suite
 	ctx              context.Context
 	testInstallation *e2e.TestInstallation
+	baseManifests    []string
+	agentGateway     bool
```
Comment (npolshakova) [inline test/kubernetes/e2e/features/backendtls/suite.go:72]: Nice! I like this pattern!

File: internal/kgateway/extensions2/plugins/backend/agentgateway/translate.go (hunk 8 above)
Comment (shashankram) [reply internal/kgateway/extensions2/plugins/backend/agentgateway/translate.go]: done

File: api/v1alpha1/mcp_backend.go [hunk 11]
```diff
@@ -4,70 +4,63 @@ import metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
...
 	// Port is the port number of the MCP target.
-	// +required
 	// +kubebuilder:validation:Minimum=1
 	// +kubebuilder:validation:Maximum=65535
 	Port int32 `json:"port"`
 
+	// Path is the URL path of the MCP target endpoint.
+	// Defaults to "/sse" for SSE protocol or "/mcp" for StreamableHTTP protocol if not specified.
+	// +optional
+	Path *string `json:"path"`
```
Comment (timflannagan) [inline api/v1alpha1/mcp_backend.go]: Just a drive-by: missing omitempty?

Comment (shashankram) [reply api/v1alpha1/mcp_backend.go]: nice catch, disappeared on rebase

File: internal/kgateway/agentgatewaysyncer/testdata/inputs/backend/backend-tls.yaml (hunk 7 above)
Comment (npolshakova) [reply internal/kgateway/agentgatewaysyncer/testdata/inputs/backend/backend-tls.yaml:75]: Cool, we should document that. Just fyi @artberger

File: api/v1alpha1/mcp_backend.go (hunk 6 above)
Comment (npolshakova) [reply api/v1alpha1/mcp_backend.go:19]: Makes sense, but do we want to document this on the MCP Backend as a go doc? Or just in the agentgateway docs? I would have expected BackendTLSPolicy to apply to all the MCP backends if I used the MCP backend name.

File: api/annotations/agentgateway.go (hunk 5 above)
Comment (npolshakova) [reply api/annotations/agentgateway.go:4]: These: https://github.com/kgateway-dev/kgateway/blob/aa46900135f66763db810fce3dd0a87255edaa41/internal/kgateway/extensions2/plugins/backend/agentgateway/mcp.go#L12 

Maybe this one too: https://github.com/kgateway-dev/kgateway/blob/aa46900135f66763db810fce3dd0a87255edaa41/pkg/agentgateway/plugins/a2a_plugin.go#L16

File: internal/kgateway/agentgatewaysyncer/testdata/inputs/backend/backend-tls.yaml (hunk 7 above)
Comment (artberger) [reply internal/kgateway/agentgatewaysyncer/testdata/inputs/backend/backend-tls.yaml:75]: Thanks for the tag, I added a note in our doc fixes PR here: https://github.com/kgateway-dev/kgateway.dev/pull/364/

File: api/annotations/agentgateway.go (hunk 5 above)
Comment (shashankram) [reply api/annotations/agentgateway.go:4]: ok will do this in a follow up since it is not directly related to this PR

File: api/v1alpha1/mcp_backend.go (hunk 6 above)
Comment (shashankram) [reply api/v1alpha1/mcp_backend.go:19]: I can in a follow up

**Review by npolshakova — APPROVED** [review]

File: api/annotations/agentgateway.go (hunk 5 above)
Comment (shashankram) [reply api/annotations/agentgateway.go:4]: Oh these are not annotations, but values for the `appProtocol` field. Can move this to api/constants and I thought about doing so previously
