### PR TITLE
Fix flake SDS test

### LINKED ISSUE #11874: Flake SDS Server E2E Test Suite
### kgateway version

main

### Kubernetes Version

n/a

### Describe the bug

Example: https://github.com/kgateway-dev/kgateway/actions/runs/16745344546/job/47402458967?pr=11873

This is a different type of flake (although in the same tests) from: https://github.com/kgateway-dev/kgateway/issues/11870

It fails because of the log.Fatal's exit with error code.

### Expected Behavior

Not to fail.

### Steps to reproduce the bug

N/A

### Additional Environment Detail

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ymesika**
# Description

The reason for the specific flake linked in #11874 is that the grpc server's Serve was called after the graceful stop in the [`runs and stops correctly` test](https://github.com/ymesika/kgateway/blob/main/internal/sds/pkg/run/run_e2e_test.go#L93) because it wasn't correctly verifying that the server is running [here](https://github.com/ymesika/kgateway/blob/main/internal/sds/pkg/run/run_e2e_test.go#L113).

This caused is some cases to reach the stop test immediately after the start check and cancel the context before the Serve() started (and therefore exit with error due to log.fatal: https://github.com/kgateway-dev/kgateway/blob/main/internal/sds/pkg/server/server.go#L84).

The PR:
1. Fixes the test to do the right checks
2. Adds some protection to make sure the stop isn't called before Serve (not perfect cover but minimizes the race)

Fixes #11874 

# Change Type

/kind flake

# Changelog

```release-note
NONE
```

# Additional Notes

Jobs runs mentioned in https://github.com/kgateway-dev/kgateway/issues/11870 seem to fail due to different error which can indeed be resolved by increasing the timeout. I will let @zhengkezhou1 cover it.

### CODE REVIEW

File: internal/sds/pkg/server/server.go [hunk 1]
```diff
@@ -79,18 +79,32 @@ func (s *Server) Run(ctx context.Context) (<-chan struct{}, error) {
...
 	slog.Info("sds server listening", "address", s.address)
+
+	// Create channels for synchronization
+	serveStarted := make(chan struct{})
+	serverStopped := make(chan struct{})
+
+	// Start the server in a goroutine
 	go func() {
+		// Signal that Serve is about to be called
+		close(serveStarted)
```
Comment (jenshu) [inline internal/sds/pkg/server/server.go:90]: do we want to do this before or after Serve is called?

Comment (ymesika) [reply internal/sds/pkg/server/server.go:90]: Serve is blocking.. That's why I mentioned it's not a perfect protection but better than before
