### PR TITLE
status: use Accepted=False,Reason=RouteRuleDropped for replaced rule

### LINKED ISSUE #11315: Stale PartiallyInvalid resource on HTTPRoutes
### kgateway version

main

### Kubernetes Version

N/A

### Describe the bug

When an HTTPRoute has configuration that leads to an error being handled in the route translator, the PartiallyInvalid status condition is set to reflect that the rule has been dropped.

However, when a user fixes the configuration error that produced the error, the PartiallyInvalid status condition is still present and stale.

### Expected Behavior

The PartiallyInvalid status condition is set correctly

### Steps to reproduce the bug

Technically requires a custom build to trigger due to #11314. If that's fixed, then the same reproducer steps outlined in that issue will suffice for reproduction. You'd first create an invalid HTTPRoute, then update to fix the issue, and validate the PartiallyInvalid status condition type sticks around.

### Additional Environment Detail

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by shashankram**
# Description
PartiallyInvalid condition has several problems:
1. It must be set only when PartiallyInvalid=True. This requires extra logic to invalidate an existing condition when there should be no PartiallyInvalid condition on an updated route status.
2. PartiallyInvalid must only be set when the route is partially invalid and not fully invalid. This requires post processing as translation merges routes with the same hostname and tracking whether a route is only partially invalid needs to group translated route rules by their parent route and check the rules for validity.

This change drops the usage of PartiallyInvalid=True in favor of Accepted=False with Reason=RouteRuleDropped. A replaced route rule will have this condition set. A route is replaced in case there are processing errors or errors on the HTTPRouteRuleMatchIr, however the condition is only set if there are processing errors from runRoutePlugins. In the case of delegating/parent routes, it is expected for the route to not have an Action set, in this case return early as the rule simply delegates and is not relevant for the final output.

# Change Type

```
/kind cleanup
```

# Changelog

```release-note
NONE
```

# Additional Notes

Resolves #11801
Resolves #11761
Resolves #11315

### CODE REVIEW

File: internal/kgateway/translator/gateway/gateway_translator_test.go [hunk 1]
```diff
@@ -718,11 +728,11 @@ var _ = DescribeTable("Basic",
 			Expect(resolvedRefs.Reason).To(Equal(string(gwv1.RouteReasonResolvedRefs)))
 
 			// Check if there's a PartiallyInvalid condition that reports the missing DirectResponse
```
Comment (timflannagan) [inline internal/kgateway/translator/gateway/gateway_translator_test.go]: nit: Need to update or remove this stale comment.

File: test/translator/test.go [hunk 2]
```diff
@@ -422,8 +448,16 @@ func AreReportsSuccess(gwNN types.NamespacedName, reportsMap reports.ReportMap)
...
+			ObjectMeta: metav1.ObjectMeta{
+				Name:      nns.Name,
+				Namespace: nns.Namespace,
+			},
+		}
+		status := reportsMap.BuildRouteStatus(context.Background(), &r, wellknown.DefaultGatewayClassName)
+
+		for ref, parentRefReport := range status.Parents {
 			for _, c := range parentRefReport.Conditions {
 				// most route conditions true is good, except RouteConditionPartiallyInvalid
```
Comment (timflannagan) [inline test/translator/test.go:462]: @shashankram Looks like copilot review flagged this. Isn't this cruft? There are several references to the partially invalid condition throughout this file.

File: pkg/pluginsdk/reporter/types.go [hunk 3]
```diff
@@ -18,6 +18,8 @@ const (
 	PolicyMergedMsg = "Merged with other policies in target(s) and attached"
 
 	PolicyOverriddenMsg = "Overridden due to conflict with higher priority policy in target(s)"
+
+	RouteRuleDroppedReason = "RouteRuleDropped"
```
Comment (timflannagan) [inline pkg/pluginsdk/reporter/types.go:23]: 👍. Do you think a godoc for this field is overkill that highlights the context around using a custom Accepted reason instead of the PartiallyInvalid type?

File: internal/kgateway/translator/irtranslator/route.go [hunk 4]
```diff
@@ -194,22 +194,39 @@ func (h *httpRouteConfigurationTranslator) envoyRoutes(
...
+	if routeReplacementErr != nil {
+		h.logger.Debug("invalid route", "error", routeReplacementErr)
+
+		// If routeAcceptanceErr is set, report Accepted=False with Reason=RouteRuleDropped
+		if routeAcceptanceErr != nil {
+			routeReport.SetCondition(reportssdk.RouteCondition{
+				Type:    gwv1.RouteConditionAccepted,
+				Status:  metav1.ConditionFalse,
+				Reason:  gwv1.RouteConditionReason(reportssdk.RouteRuleDroppedReason),
+				Message: fmt.Sprintf("Dropped Rule (%d): %v", in.MatchIndex, routeProcessingErr),
```
Comment (timflannagan) [inline internal/kgateway/translator/irtranslator/route.go]: This only reports routeProcessingErr, but the condition is triggered when routeAcceptanceErr != nil. The routeAcceptanceErr may contain additional context from in.RouteAcceptanceError?

File: internal/kgateway/translator/irtranslator/route.go [hunk 5]
```diff
@@ -194,22 +194,39 @@ func (h *httpRouteConfigurationTranslator) envoyRoutes(
...
-		// TODO: we may want to aggregate all these errors per http route object and report one message?
-		routeReport.SetCondition(reportssdk.RouteCondition{
-			Type:    gwv1.RouteConditionPartiallyInvalid,
-			Status:  metav1.ConditionTrue,
-			Reason:  gwv1.RouteReasonUnsupportedValue,
-			Message: fmt.Sprintf("Dropped Rule (%d): %v", in.MatchIndex, err),
-		})
+
+	// routeAcceptanceErr is used to set the Accepted=false,Reason=RouteRuleDropped condition on the route
+	routeAcceptanceErr := errors.Join(routeProcessingErr, in.RouteAcceptanceError)
```
Comment (timflannagan) [inline internal/kgateway/translator/irtranslator/route.go:206]: Where is in.RouteAcceptanceError set with these changes? Is this just for future proofing?

**Review by timflannagan — COMMENTED** [review]
This will also resolve https://github.com/kgateway-dev/kgateway/issues/11761 & https://github.com/kgateway-dev/kgateway/issues/11315.

One question around in.RouteAcceptanceError and a couple of nits, but high-level LGTM.

File: test/translator/test.go (hunk 2 above)
Comment (shashankram) [reply test/translator/test.go:462]: False alarms. If we ever use PartiallyInvalid we will need to add those back to the Status helpers again, so I just left it since the status checker code is Gateway API specific and nothing to do with our impl.

File: internal/kgateway/translator/irtranslator/route.go (hunk 4 above)
Comment (shashankram) [reply internal/kgateway/translator/irtranslator/route.go]: Good catch, typo from a refactor, will fix

File: internal/kgateway/translator/irtranslator/route.go (hunk 5 above)
Comment (shashankram) [reply internal/kgateway/translator/irtranslator/route.go:206]: Yes, @lgadban will set this when ExtensionRefs lookup fails

File: pkg/pluginsdk/reporter/types.go (hunk 3 above)
Comment (shashankram) [reply pkg/pluginsdk/reporter/types.go:23]: Done

File: internal/kgateway/translator/irtranslator/route.go [hunk 6]
```diff
@@ -194,22 +194,39 @@ func (h *httpRouteConfigurationTranslator) envoyRoutes(
...
-			return nil
-		} else {
-			err = errors.New("no action specified")
-		}
+	// If routeProcessingErr is nil, check if the route has an action for non-delegating routes
+	// to treat this as an error that should result in route replacement.
+	// A delegating(parent) route does not need to have an output Action on itself,
+	// so do not treat it as an error
+	if routeProcessingErr == nil && out.GetAction() == nil && !in.Delegates {
+		routeProcessingErr = errors.New("no action specified")
```
Comment (lgadban) [inline internal/kgateway/translator/irtranslator/route.go:202]: I know it's not directly related to your change but do we know of a case where action == nil in the non-delegating case? i.e. what scenario actually ends up here?

**Review by timflannagan — APPROVED** [review]
The translateTcpFilterChain method also has some commented out code around setting the RouteConditionPartiallyInvalid condition, but existing problem from the initial 2.0 refactor work.

File: pkg/pluginsdk/reporter/types.go (hunk 3 above)
Comment (lgadban) [reply pkg/pluginsdk/reporter/types.go:23]: I was going to ask if this is actually something that should move to `api/`?

That may be a larger item so godoc should be sufficient for now?

File: internal/kgateway/query/httproute.go [hunk 7]
```diff
@@ -304,7 +303,7 @@ func (r *gatewayQueries) fetchRoutesByRef(
 			// Lookup a specific child route by its name
 			route := r.collections.Routes.FetchHttp(kctx, delegatedNs, string(backendRef.Name))
 			if route == nil {
-				return nil, errors.New("not found")
+				return nil, ErrUnresolvedReference
```
Comment (lgadban) [inline internal/kgateway/query/httproute.go:306]: assuming this is fine? assuming it's only changing the error in delegation to match the error from the non-delegation case?

File: internal/kgateway/translator/irtranslator/route.go (hunk 6 above)
Comment (shashankram) [reply internal/kgateway/translator/irtranslator/route.go:202]: This was there from day0 to guard against invalid/dropped actions. Delegation has had to work around this. If we decide to remove it, it must be a separate change

Comment (timflannagan) [reply internal/kgateway/translator/irtranslator/route.go:202]: Direct response plugin is the primary (and potentially only?) scenario where this logic is still relevant for non-delegation scenarios.

Comment (timflannagan) [reply internal/kgateway/translator/irtranslator/route.go:202]: Potentially some edge case in translateRouteAction as well.

File: internal/kgateway/query/httproute.go (hunk 7 above)
Comment (shashankram) [reply internal/kgateway/query/httproute.go:306]: This makes the lookup errors for delegation consistent. Just a few lines below we return ErrUnresolvedReference so the previous error was resulting in inconsistent messages depending on the lookup ref (wildcard, singular, label, etc.)

File: pkg/pluginsdk/reporter/types.go (hunk 3 above)
Comment (shashankram) [reply pkg/pluginsdk/reporter/types.go:23]: Yes we could move this to `api/` in a separate PR. I don't feel strongly about it
