### PR TITLE
deployer: Respect GWP overrides for Istio integration

### LINKED ISSUE #11004: GW params not applied to istio-proxy container for sidecar integration
### kgateway version

2.0.0-main

### Kubernetes Version

1.30

### Describe the bug

When enabling the Istio sidecar integration, it seems that the custom GatewayParameters are not getting applied to the `istio-proxy` container in the gateway proxy. 

1. Install Istio in sidecar mode. I am using the Gloo operator in GM https://docs.solo.io/gloo-mesh-enterprise/latest/istio/operator/install/#install which creates a revision istiod (`istiod-gloo`) 
2. Get kgateway Helm values. 
```
helm get values kgateway -n kgateway-system -o yaml > kgateway.yaml
open kgateway.yaml
```
3. Add the following. 
```
controller:
  extraEnv:
    KGW_ENABLE_ISTIO_AUTO_MTLS: true
```

4. Upgrade. 
```
helm upgrade -i --namespace kgateway-system --version v2.0.0-main kgateway oci://cr.kgateway.dev/kgateway-dev/charts/kgateway -f kgateway.yaml
```

5. Create custom GW params. 
```
kubectl apply -f- <<EOF
apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayParameters
metadata:
  name: custom-gw-params
  namespace: kgateway-system
spec:
  kube: 
    istio:
      istioProxyContainer:
        istioDiscoveryAddress: istiod-gloo.istio-system.svc:15012
        istioMetaClusterId: $ClUSTER_NAME
        istioMetaMeshId: $CLUSTER_NAME
EOF
```

6. Update GW
```
kubectl apply -f- <<EOF
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: http
  namespace: kgateway-system
spec:
  gatewayClassName: kgateway
  infrastructure:
    parametersRef:
      name: custom-gw-params
      group: gateway.kgateway.dev
      kind: GatewayParameters
  listeners:
  - protocol: HTTP
    port: 8080
    name: http
    allowedRoutes:
      namespaces:
        from: All
EOF
```

7. Check that the http gateway proxy restarts and comes up with 3 containers. 
8. Check the logs of the istio-proxy container. they will show it is using istiod instead of istiod-gloo
```
2025-03-31T18:51:21.488003Z	warn	concurrency is set to 0, which will use a thread per CPU on the host. However, CPU limit is set lower. This is not recommended and may lead to performance issues. CPU count: 4, CPU Limit: 0.
2025-03-31T18:51:21.488349Z	info	Effective config: binaryPath: /usr/local/bin/envoy
configPath: ./etc/istio/proxy
controlPlaneAuthPolicy: MUTUAL_TLS
discoveryAddress: istiod.istio-system.svc:15012
drainDuration: 45s
proxyAdminPort: 15000
serviceCluster: istio-proxy
statNameLength: 189
statusPort: 15020
terminationDrainDuration: 5s
```

### Expected Behavior

The http gateway should come up with 3 containers and point to the correct istiod deployment.

### Steps to reproduce the bug

see above. 

### Additional Environment Detail

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by timflannagan**
# Description

The issue was that the merge logic was preventing valid GWP overrides because:

1. The in-memory default GatewayParameters always had these Istio fields set
2. The merge function used the in-memory parameters as the destination
3. The merge logic only copied from source if destination was nil
4. Therefore, valid overrides in user-provided GatewayParameters were being ignored

This effectively made these Istio configuration fields immutable once set in the default parameters, which was not the intended behavior.

Additionally, the GWP configuration outlined in the #11004 issue are configuring fields environment variables on the proxy deployment under-the-hood and the merging-related functions in the deployer suite did not assert on the expected envvars on the istio proxy container.

Closes #11004.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: internal/kgateway/deployer/merge.go
Comment (timflannagan) [inline internal/kgateway/deployer/merge.go:1]: We verified that the merging logic in the deepMergeIstioContainer function was a special case. The other sub-merge functions are consistent where they check whether `src.GetSomeField() != nil` to merge into the base.

File: internal/kgateway/deployer/deployer_test.go [hunk 1]
```diff
@@ -1450,6 +1448,23 @@ var _ = Describe("Deployer", func() {
...
+				Name:      "ISTIO_META_MESH_ID",
+				Value:     *inp.overrideGwp.Spec.Kube.Istio.IstioProxyContainer.IstioMetaMeshId,
+				ValueFrom: nil,
+			}))
+			Expect(istioProxyContainer.Env).To(ContainElement(corev1.EnvVar{
+				Name:      "ISTIO_META_CLUSTER_ID",
+				Value:     *inp.overrideGwp.Spec.Kube.Istio.IstioProxyContainer.IstioMetaClusterId,
+				ValueFrom: nil,
+			}))
+
```
Comment (timflannagan) [inline internal/kgateway/deployer/deployer_test.go:1467]: Verified before & after the merge.go change these tests were setting the envvars correctly based on the input override GWP object supplied to this test. Before this change, we had to use the default values that are outlined in the in-memory GWP representation, and then after we had to change the value to be consistent with the GWP coniguration.

**Review by lgadban — APPROVED** [review]

**Review by jenshu — APPROVED** [review]

**Review by npolshakova — APPROVED** [review]
